build:
  version: "3.0"

department:
  message: "Welcome to AssetManagement Department local APIs"
  contactDetails:
    - name: "Sumedh Pagare - Developer"
    - email: "sumedh@gmail.com"
  onCallSupport:
    - (111) 111-1234
    - (111) 111-9874