server:
  port: 9094
spring:
  application:
    name: asset
  datasource:
    url: jdbc:mysql://localhost:3399/assetmanagement_micro_db
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    connection-timeout: 10s

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "Asset Microservice"
    description: "This microservice handles the CRUD Operations of Asset and Asset Types"
    version: "1.0"
