services:
  rabbitmq:
    container_name: "rabbitmq"
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    
  configserver:
    image: "yashpalgawali/configserver:v1"
    container_name: "ms-configserver"
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 200m
    networks:
      - assetmanagement

  company:
    image: "yashpalgawali/company:v1"
    container_name: "ms-company"
    ports:
      - "9091:9091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - assetmanagement
    environment:
      SPRING_APPLICATION_NAME: "company"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"


  department:
    image: "yashpalgawali/department:v1"
    container_name: "ms-department"
    ports:
      - "9092:9092"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - assetmanagement
    environment:
      SPRING_APPLICATION_NAME: "department"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "default"


networks:
  assetmanagement:
    driver: "bridge"