server:
  port: 8072
spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*" 
    access:
      default: unrestricted
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted
    health:
      probes:
        enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Asset Management APi Gateway server"
    version: "1.0.0"

endpoints:
  shutdown:
    enabled: true

logging:
  level:
    com:
      example:
        demo: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000
